### ISSUE TITLE
Use an abstract BenchmarkProblem class

### ISSUE THREAD

**Issue by tschm** [cvxpy/benchmarks#18]
with setup, and time_compile_problem

put np.random.seed into this mother class...

Use solver as an argument to time_compile_problem fct.

**Comment by phschiele** [comment]
Good points and agree that it would be cleaner.
In this case, we strictly followed the docs from asv: https://asv.readthedocs.io/en/stable/writing_benchmarks.html
I'm not sure if it would try to run the abstract class if we introduced one.
I expect the set of benchmarks not to change too frequently, so let's keep it for now.
