### ISSUE TITLE
MNIST SVM benchmark submission

### ISSUE THREAD

**Issue by rileyjmurray** [cvxpy/benchmarks#2]
Someone posted a CVXPY formulation of SVM for MNIST. Their example runs in Google Colab and used essentially no vectorization. It took multiple days to compile: https://github.com/cvxpy/cvxpy/discussions/1777#discussioncomment-2752686.

**Comment by phschiele** [comment]
Thanks for cross-referencing the discussion here, @rileyjmurray 
I suppose the most important takeaway is that vectorization is super important :D
Still, with a ~6-second compile time it would make a good candidate to be included in the benchmark suite!

**Comment by phschiele** [comment]
@rileyjmurray: @parthb83 has added an example for SVM #8
One consideration for the benchmarks is to make them easy to read/maintain.
I'd be a bit hesitant to add the linked example, as it is not very readable, and comes with additional dependencies and data.

With the cleaner implementation of an SVM, would it be fine for you to close this issue?

**Comment by rileyjmurray** [comment]
Fine with me to close!
